theme: jekyll-theme-midnight
title: "Leuck Family Reunion"
gitorg: "https://github.com/jm1021/leuck_reunion"
description: "June 26, 2023"
google_analytics:
twitter: "https://twitter.com/Ch_JesusChrist"
twitterid: "@Ch_JesusChrist"
webserver: "https://www.churchofjesuschrist.org/"
webserverid: "churchofjesuschrist"
